# Generated by Django 3.1.2 on 2020-12-05 08:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140, validators=[django.core.validators.MinLengthValidator(5, 'Titile is too short'), django.core.validators.MaxLengthValidator(140, 'Title is too long')], verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('body', models.TextField(verbose_name='Post Content')),
                ('url', models.CharField(max_length=250, verbose_name='Post URL')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
