# Generated by Django 3.1.2 on 2020-12-19 07:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20201216_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=140, validators=[django.core.validators.MinLengthValidator(5, 'Title is too short'), django.core.validators.MaxLengthValidator(140, 'Title is too long')], verbose_name='Title'),
        ),
    ]
