# Generated by Django 3.1.2 on 2020-11-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Book Name')),
                ('author', models.CharField(max_length=150, verbose_name='Author')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('published_on', models.DateField(verbose_name='Published on')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
