# Generated by Django 3.1.2 on 2020-11-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('science', 'Science'), ('tech', 'Technology'), ('sports', 'Sports'), ('ent', 'Entertainment')], default=None, max_length=50, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
