# Generated by Django 3.1.2 on 2020-12-04 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(500)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Name is too short')], verbose_name='Book Name'),
        ),
    ]
